/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_glrender_MainActivity */

#ifndef _Included_com_example_glrender_MainActivity
#define _Included_com_example_glrender_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_glrender_MainActivity
 * Method:    nativeSetApkPath
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_example_glrender_MainActivity_nativeSetApkPath
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_example_glrender_MainActivity
 * Method:    nativeOnStart
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_glrender_MainActivity_nativeOnStart
  (JNIEnv *, jclass);

/*
 * Class:     com_example_glrender_MainActivity
 * Method:    nativeOnResume
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_glrender_MainActivity_nativeOnResume
  (JNIEnv *, jclass);

/*
 * Class:     com_example_glrender_MainActivity
 * Method:    nativeOnPause
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_glrender_MainActivity_nativeOnPause
  (JNIEnv *, jclass);

/*
 * Class:     com_example_glrender_MainActivity
 * Method:    nativeOnStop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_glrender_MainActivity_nativeOnStop
  (JNIEnv *, jclass);

/*
 * Class:     com_example_glrender_MainActivity
 * Method:    nativeSetSurface
 * Signature: (Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_com_example_glrender_MainActivity_nativeSetSurface
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
